import type { EditorTheme } from "./CodeEditor";

export const EDITOR_FONT = "'IBM Plex Mono', ui-monospace, monospace";

export const phosphorTheme: EditorTheme = {
  name: "phosphor",
  data: {
    base: "vs-dark",
    inherit: true,
    rules: [
      { token: "", foreground: "f3d9a4" },
      { token: "comment", foreground: "7d6339", fontStyle: "italic" },
      { token: "keyword", foreground: "ffc940", fontStyle: "bold" },
      { token: "string", foreground: "5cff7a" },
      { token: "string.escape", foreground: "b4ffbf" },
      { token: "number", foreground: "ff8a3d" },
      { token: "type", foreground: "ffb000" },
      { token: "tag", foreground: "ff8a3d" },
      { token: "identifier", foreground: "f3d9a4" },
      { token: "delimiter", foreground: "a08550" },
      { token: "delimiter.bracket", foreground: "c9a35a" },
      { token: "operator", foreground: "ffb000" },
    ],
    colors: {
      "editor.background": "#0d0b06",
      "editor.foreground": "#f3d9a4",
      "editorCursor.foreground": "#ffb000",
      "editorCursor.background": "#0b0904",
      "editor.lineHighlightBackground": "#1a150b",
      "editor.lineHighlightBorder": "#00000000",
      "editor.selectionBackground": "#ffb00040",
      "editor.inactiveSelectionBackground": "#ffb00020",
      "editor.selectionHighlightBackground": "#ffb00018",
      "editor.wordHighlightBackground": "#ffb00018",
      "editor.findMatchBackground": "#ffb00055",
      "editor.findMatchHighlightBackground": "#ffb00025",
      "editorLineNumber.foreground": "#4f4122",
      "editorLineNumber.activeForeground": "#ffb000",
      "editorGutter.background": "#0d0b06",
      "editorIndentGuide.background1": "#2a2110",
      "editorIndentGuide.activeBackground1": "#5a461c",
      "editorWhitespace.foreground": "#33280f",
      "editorBracketMatch.background": "#ffb00020",
      "editorBracketMatch.border": "#ffb00080",
      "editorBracketHighlight.foreground1": "#ffb000",
      "editorBracketHighlight.foreground2": "#ff8a3d",
      "editorBracketHighlight.foreground3": "#5cff7a",
      "editorBracketHighlight.foreground4": "#ffc940",
      "editorBracketHighlight.foreground5": "#ff8a3d",
      "editorBracketHighlight.foreground6": "#5cff7a",
      "editorError.foreground": "#ff5a4a",
      "editorWarning.foreground": "#ff8a3d",
      "editorWidget.background": "#120f08",
      "editorWidget.border": "#5a461c",
      "editorSuggestWidget.background": "#120f08",
      "editorSuggestWidget.border": "#5a461c",
      "editorSuggestWidget.foreground": "#f3d9a4",
      "editorSuggestWidget.highlightForeground": "#ffc940",
      "editorSuggestWidget.selectedBackground": "#ffb00030",
      "editorHoverWidget.background": "#120f08",
      "editorHoverWidget.border": "#5a461c",
      "scrollbarSlider.background": "#ffb0001f",
      "scrollbarSlider.hoverBackground": "#ffb00040",
      "scrollbarSlider.activeBackground": "#ffb00066",
      "scrollbar.shadow": "#00000000",
      focusBorder: "#ffb00000",
    },
  },
};
